/var/log/netmon/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    create 0640 netmon netmon
    sharedscripts
    postrotate
        systemctl reload netmon-engine netmon-api > /dev/null 2>&1 || true
    endscript
}
